[package]
name = "cdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = {version = "2.1.4", features = ["sqlite"]}
dotenv = "0.15.0"
clap = "4.4.11"
matches = "0.1.10"
unreachable = "1.0.0"
